name: jsc-cordex
channels:
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib
  - seaborn
  - regionmask
  - intake-esm
  - pandas
  - openpyxl
  - xlsxwriter
  - dask
  - netcdf4
  - aiohttp
