name: eval-book
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cartopy
  - matplotlib-base
  - regionmask
  - xarray
  - cf_xarray
  - cftime
  - flox
  - netCDF4
  - h5netcdf
  - xesmf
  - cdo
  - python-cdo
  - jupyter-book
  - intake-esm
  - ghp-import
  - gcsfs
  - fsspec
  - requests
  - aiohttp
  - nbconvert
  - pip:
    - git+https://github.com/euro-cordex/evaltools # always use main for now
    - git+https://github.com/euro-cordex/py-cordex # always use main for now
