name: deploy jupyterbook

on:
  workflow_dispatch:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v5

    # Install dependencies
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install jupyter-book

    # Build the book
    - name: Build the book
      run: |
        cp README.md ./eval-book
        jupyter-book build eval-book

    # Upload the book's HTML as an artifact
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: "eval-book/_build/html"

    # Deploy the book's HTML to GitHub Pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: eval-book/_build/html
